### ISSUE TITLE
不能柔和跳转

### ISSUE THREAD

**Issue by bxl0608** [bifan-wei/LrcView#1]
为什么我用你的这个控件不能柔和的跳到指定时间呢，它是一下子就跳过去了！

**Comment by bxl0608** [comment]
我在播放器时间更新的回调中写了smoothScrollToTime(time)，它不能柔和的滚动，然后我在lrcView空间写了个setAutomaticDurtion(0)  它能一跳一跳的，一点都不柔和，如果我传别的参数它又不自动滚动了

**Comment by bifan-wei** [comment]
播放器时间更新不要一直刷新，试一试每隔一秒刷新一次时间与调用smoothScrollToTime

**Comment by bxl0608** [comment]
> 播放器时间更新不要一直刷新，试一试每隔一秒刷新一次时间与调用smoothScrollToTime

那我的歌词会同步吗，有的歌词中间是没有1s间隔的。

**Comment by bifan-wei** [comment]
没问题的，歌词会根据时间显示最近的那句歌词，歌词没错的话就基本没问题。时间刷新太频繁，动画执行时间过短，建议启动定时器每一秒刷新一次歌词与播放器显示的时间

**Comment by bxl0608** [comment]
>           没问题的，歌词会根据时间显示最近的那句歌词，歌词没错的话就基本没问题。时间刷新太频繁，动画执行时间过短，建议启动定时器每一秒刷新一次歌词与播放器显示的时间

怪不得我运行起来特别卡，我间隔100ms刷新一次，我手机跑起来特别吃力！谢谢了，我试试去

**Comment by bxl0608** [comment]
> 没问题的，歌词会根据时间显示最近的那句歌词，歌词没错的话就基本没问题。时间刷新太频繁，动画执行时间过短，建议启动定时器每一秒刷新一次歌词与播放器显示的时间

你好，我用你说的每隔1秒刷新一次，现在可以柔和滚动了，但是还是有问题，当我有一段歌词太快了的时候，它来不及滚动就要显示下一行歌词内容，然后它的选中歌词就不在中间了。我不知道怎么上传截图。。。

**Comment by bifan-wei** [comment]
这种情况很少见啊，一般不会遇到这种歌词。方便的话把歌词跟音乐文件发我一下1198330662@qq.com

**Comment by bxl0608** [comment]
> 这种情况很少见啊，一般不会遇到这种歌词。方便的话把歌词跟音乐文件发我一下[1198330662@qq.com](mailto:1198330662@qq.com)

我发过去了一个demo，你看一下那个内容，然后看看是不是这个问题呢

**Comment by bifan-wei** [comment]
我下了那歌与歌词，在我的项目上播放，没有任何问题，你看看是不是你处理的不对

**Comment by bxl0608** [comment]
> 我下了那歌与歌词，在我的项目上播放，没有任何问题，你看看是不是你处理的不对

我就只改了下样式，然后在countdowntimer里面更新歌词，间隔1s，但是它就跟我就像项目不兼容，出现了我之前说的那个题，还有别的一些小bug，但是基本用法不就这几条呀，还需要别的设置吗？

**Comment by bifan-wei** [comment]
你把歌词字体调大点看看，还不行就贴下你调用的代码看看

**Comment by bxl0608** [comment]
> 你把歌词字体调大点看看，还不行就贴下你调用的代码看看

好的，明天我试试看，谢谢了。

**Comment by bxl0608** [comment]
> 你把歌词字体调大点看看，还不行就贴下你调用的代码看看

能把你app发我一下看看吗？我app使用的时候总是有滚动

**Comment by bxl0608** [comment]
> 你把歌词字体调大点看看，还不行就贴下你调用的代码看看

能把你app发我一份看看吗。我app滚动总是有bug
